#!/bin/sh
set -e
USER=${deb.user}

case "$1" in
    purge)
        if which deluser >/dev/null 2>&1 ; then
            deluser --quiet --system $USER > /dev/null || true
        else
            echo >&2 "$USER system account not deleted because deluser command was not found"
        fi
    ;;
    
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    
    *)
        echo "unknown args for postrm \`$1'" >&2
        exit 1
    ;;
esac
exit 0