#!/bin/sh
set -e
SERVICENAME=${deb.servicename}

case "$1" in
    remove|purge)
        service $SERVICENAME stop || true
        ;;

    upgrade|deconfigure)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0